replicaCount: 1

image:
  repository: ghcr.io/lucas2kdk/hailmary-helloworld
  tag: sha-353fed6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "tailscale"
  host: hello-world-prod
  path: /
  pathType: Prefix

resources: {}
