apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "hello-world.fullname" . }}-allow-tailscale
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: tailscale
